name: Domain Pipeline

on:
  push:
    branches:
      - main

jobs:
  modify_domain:
    runs-on: ubuntu-latest

    env:
      API_URL: ${{ secrets.API_URL }}
      API_TOKEN: ${{ secrets.API_TOKEN }}
      DOMAINS_FILE: ${{ secrets.DOMAINS_FILE }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Python Script
        run: |
          python parser.py "$API_URL" "$API_TOKEN" "$DOMAINS_FILE"

